# Generated by Django 3.0.3 on 2020-04-26 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.TextField(default='Remote')),
                ('techstack', models.TextField(default='N/A')),
                ('timestamp', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=True)),
                ('applicants', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('accept_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.ExtendedUser')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Postings')),
            ],
        ),
    ]
