# Generated by Django 3.0.4 on 2020-04-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='location',
            field=models.TextField(default='Remote'),
        ),
        migrations.AddField(
            model_name='postings',
            name='techstack',
            field=models.TextField(default='N/A'),
        ),
    ]
