# Generated by Django 3.0.4 on 2020-04-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200403_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postings',
            old_name='name',
            new_name='title',
        ),
    ]
