# Generated by Django 3.0.3 on 2020-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='image',
            field=models.TextField(default='http://via.placeholder.com/150'),
        ),
    ]
