# Generated by Django 3.0.3 on 2020-04-25 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200403_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
