# Generated by Django 3.0.3 on 2020-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='description',
            field=models.TextField(default='This user has not provided an about me.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default='This organization has not provided a description.'),
        ),
    ]
