# Generated by Django 2.2.5 on 2020-02-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('poster', models.ForeignKey(default=None, on_delete='CASCADE', to='users.Organization')),
            ],
        ),
    ]
