# Generated by Django 3.0.3 on 2020-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200426_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='image',
            field=models.TextField(default='http://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.TextField(default='http://via.placeholder.com/150'),
        ),
    ]
