# Generated by Django 2.2.5 on 2020-02-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_postings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postings',
            old_name='poster',
            new_name='organization',
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_user', models.ForeignKey(default=None, on_delete=models.CASCADE, to='users.ExtendedUser')),
                ('post', models.ForeignKey(default=None, on_delete=models.CASCADE, to='users.Postings')),
            ],
        ),
    ]
