# Generated by Django 2.2.5 on 2020-02-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200204_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postings',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Postings',
        ),
    ]
