from django import forms
from . import models
from django.contrib.auth.models import User


class CreatePost(forms.ModelForm):
    class Meta:
        loc_choices = (
            ('Remote', 'Remote'),
            ('AK (All)', 'AK (All)'),
            ('AK (North)', 'AK (North)'),
            ('AK (Central)', 'AK (Central)'),
            ('AK (South)', 'AK (South)'),
            ('AL (All)', 'AL (All)'),
            ('AL (North)', 'AL (North)'),
            ('AL (Central)', 'AL (Central)'),
            ('AL (South)', 'AL (South)'),
            ('AR (All)', 'AR (All)'),
            ('AR (North)', 'AR (North)'),
            ('AR (Central)', 'AR (Central)'),
            ('AR (South)', 'AR (South)'),
            ('AZ (All)', 'AZ (All)'),
            ('AZ (North)', 'AZ (North)'),
            ('AZ (Central)', 'AZ (Central)'),
            ('AZ (South)', 'AZ (South)'),
            ('CA (All)', 'CA (All)'),
            ('CA (North)', 'CA (North)'),
            ('CA (Central)', 'CA (Central)'),
            ('CA (South)', 'CA (South)'),
            ('CO (All)', 'CO (All)'),
            ('CO (North)', 'CO (North)'),
            ('CO (Central)', 'CO (Central)'),
            ('CO (South)', 'CO (South)'),
            ('CT (All)', 'CT (All)'),
            ('CT (North)', 'CT (North)'),
            ('CT (Central)', 'CT (Central)'),
            ('CT (South)', 'CT (South)'),
            ('DE (All)', 'DE (All)'),
            ('DE (North)', 'DE (North)'),
            ('DE (Central)', 'DE (Central)'),
            ('DE (South)', 'DE (South)'),
            ('FL (All)', 'FL (All)'),
            ('FL (North)', 'FL (North)'),
            ('FL (Central)', 'FL (Central)'),
            ('FL (South)', 'FL (South)'),
            ('GA (All)', 'GA (All)'),
            ('GA (North)', 'GA (North)'),
            ('GA (Central)', 'GA (Central)'),
            ('GA (South)', 'GA (South)'),
            ('HI (All)', 'HI (All)'),
            ('HI (North)', 'HI (North)'),
            ('HI (Central)', 'HI (Central)'),
            ('HI (South)', 'HI (South)'),
            ('IA (All)', 'IA (All)'),
            ('IA (North)', 'IA (North)'),
            ('IA (Central)', 'IA (Central)'),
            ('IA (South)', 'IA (South)'),
            ('ID (All)', 'ID (All)'),
            ('ID (North)', 'ID (North)'),
            ('ID (Central)', 'ID (Central)'),
            ('ID (South)', 'ID (South)'),
            ('IL (All)', 'IL (All)'),
            ('IL (North)', 'IL (North)'),
            ('IL (Central)', 'IL (Central)'),
            ('IL (South)', 'IL (South)'),
            ('IN (All)', 'IN (All)'),
            ('IN (North)', 'IN (North)'),
            ('IN (Central)', 'IN (Central)'),
            ('IN (South)', 'IN (South)'),
            ('KS (All)', 'KS (All)'),
            ('KS (North)', 'KS (North)'),
            ('KS (Central)', 'KS (Central)'),
            ('KS (South)', 'KS (South)'),
            ('KY (All)', 'KY (All)'),
            ('KY (North)', 'KY (North)'),
            ('KY (Central)', 'KY (Central)'),
            ('KY (South)', 'KY (South)'),
            ('LA (All)', 'LA (All)'),
            ('LA (North)', 'LA (North)'),
            ('LA (Central)', 'LA (Central)'),
            ('LA (South)', 'LA (South)'),
            ('MA (All)', 'MA (All)'),
            ('MA (North)', 'MA (North)'),
            ('MA (Central)', 'MA (Central)'),
            ('MA (South)', 'MA (South)'),
            ('MD (All)', 'MD (All)'),
            ('MD (North)', 'MD (North)'),
            ('MD (Central)', 'MD (Central)'),
            ('MD (South)', 'MD (South)'),
            ('ME (All)', 'ME (All)'),
            ('ME (North)', 'ME (North)'),
            ('ME (Central)', 'ME (Central)'),
            ('ME (South)', 'ME (South)'),
            ('MI (All)', 'MI (All)'),
            ('MI (North)', 'MI (North)'),
            ('MI (Central)', 'MI (Central)'),
            ('MI (South)', 'MI (South)'),
            ('MN (All)', 'MN (All)'),
            ('MN (North)', 'MN (North)'),
            ('MN (Central)', 'MN (Central)'),
            ('MN (South)', 'MN (South)'),
            ('MO (All)', 'MO (All)'),
            ('MO (North)', 'MO (North)'),
            ('MO (Central)', 'MO (Central)'),
            ('MO (South)', 'MO (South)'),
            ('MS (All)', 'MS (All)'),
            ('MS (North)', 'MS (North)'),
            ('MS (Central)', 'MS (Central)'),
            ('MS (South)', 'MS (South)'),
            ('MT (All)', 'MT (All)'),
            ('MT (North)', 'MT (North)'),
            ('MT (Central)', 'MT (Central)'),
            ('MT (South)', 'MT (South)'),
            ('NC (All)', 'NC (All)'),
            ('NC (North)', 'NC (North)'),
            ('NC (Central)', 'NC (Central)'),
            ('NC (South)', 'NC (South)'),
            ('ND (All)', 'ND (All)'),
            ('ND (North)', 'ND (North)'),
            ('ND (Central)', 'ND (Central)'),
            ('ND (South)', 'ND (South)'),
            ('NE (All)', 'NE (All)'),
            ('NE (North)', 'NE (North)'),
            ('NE (Central)', 'NE (Central)'),
            ('NE (South)', 'NE (South)'),
            ('NH (All)', 'NH (All)'),
            ('NH (North)', 'NH (North)'),
            ('NH (Central)', 'NH (Central)'),
            ('NH (South)', 'NH (South)'),
            ('NJ (All)', 'NJ (All)'),
            ('NJ (North)', 'NJ (North)'),
            ('NJ (Central)', 'NJ (Central)'),
            ('NJ (South)', 'NJ (South)'),
            ('NM (All)', 'NM (All)'),
            ('NM (North)', 'NM (North)'),
            ('NM (Central)', 'NM (Central)'),
            ('NM (South)', 'NM (South)'),
            ('NV (All)', 'NV (All)'),
            ('NV (North)', 'NV (North)'),
            ('NV (Central)', 'NV (Central)'),
            ('NV (South)', 'NV (South)'),
            ('NY (All)', 'NY (All)'),
            ('NY (North)', 'NY (North)'),
            ('NY (Central)', 'NY (Central)'),
            ('NY (South)', 'NY (South)'),
            ('OH (All)', 'OH (All)'),
            ('OH (North)', 'OH (North)'),
            ('OH (Central)', 'OH (Central)'),
            ('OH (South)', 'OH (South)'),
            ('OK (All)', 'OK (All)'),
            ('OK (North)', 'OK (North)'),
            ('OK (Central)', 'OK (Central)'),
            ('OK (South)', 'OK (South)'),
            ('OR (All)', 'OR (All)'),
            ('OR (North)', 'OR (North)'),
            ('OR (Central)', 'OR (Central)'),
            ('OR (South)', 'OR (South)'),
            ('PA (All)', 'PA (All)'),
            ('PA (North)', 'PA (North)'),
            ('PA (Central)', 'PA (Central)'),
            ('PA (South)', 'PA (South)'),
            ('RI (All)', 'RI (All)'),
            ('RI (North)', 'RI (North)'),
            ('RI (Central)', 'RI (Central)'),
            ('RI (South)', 'RI (South)'),
            ('SC (All)', 'SC (All)'),
            ('SC (North)', 'SC (North)'),
            ('SC (Central)', 'SC (Central)'),
            ('SC (South)', 'SC (South)'),
            ('SD (All)', 'SD (All)'),
            ('SD (North)', 'SD (North)'),
            ('SD (Central)', 'SD (Central)'),
            ('SD (South)', 'SD (South)'),
            ('TN (All)', 'TN (All)'),
            ('TN (North)', 'TN (North)'),
            ('TN (Central)', 'TN (Central)'),
            ('TN (South)', 'TN (South)'),
            ('TX (All)', 'TX (All)'),
            ('TX (North)', 'TX (North)'),
            ('TX (Central)', 'TX (Central)'),
            ('TX (South)', 'TX (South)'),
            ('UT (All)', 'UT (All)'),
            ('UT (North)', 'UT (North)'),
            ('UT (Central)', 'UT (Central)'),
            ('UT (South)', 'UT (South)'),
            ('VA (All)', 'VA (All)'),
            ('VA (North)', 'VA (North)'),
            ('VA (Central)', 'VA (Central)'),
            ('VA (South)', 'VA (South)'),
            ('VT (All)', 'VT (All)'),
            ('VT (North)', 'VT (North)'),
            ('VT (Central)', 'VT (Central)'),
            ('VT (South)', 'VT (South)'),
            ('WA (All)', 'WA (All)'),
            ('WA (North)', 'WA (North)'),
            ('WA (Central)', 'WA (Central)'),
            ('WA (South)', 'WA (South)'),
            ('WI (All)', 'WI (All)'),
            ('WI (North)', 'WI (North)'),
            ('WI (Central)', 'WI (Central)'),
            ('WI (South)', 'WI (South)'),
            ('WV (All)', 'WV (All)'),
            ('WV (North)', 'WV (North)'),
            ('WV (Central)', 'WV (Central)'),
            ('WV (South)', 'WV (South)'),
            ('WY (All)', 'WY (All)'),
            ('WY (North)', 'WY (North)'),
            ('WY (Central)', 'WY (Central)'),
            ('WY (South)', 'WY (South)'),
        )
        tech_choices = (
            ('Backend', 'Backend'),
            ('Frontend', 'Frontend'),
            ('Cloud', 'Cloud'),
            ('Python', 'Python'),
            ('C++', 'C++'),
            ('Android Development', 'Android Development'),
            (' C', ' C'),
            (' C#', ' C#'),
            ('PHP', 'PHP'),
            ('Git', 'Git'),
            ('R', 'R'),
            ('SQL', 'SQL'),
            ('JavaScript', 'JavaScript'),
            ('Java', 'Java'),
            ('HTML/CSS', 'HTML/CSS'),
            ('AWS', 'AWS'),
            ('Azure', 'Azure'),
            ('Google Cloud', 'Google Cloud'),
            ('Linux', 'Linux'),
            ('Data Warehousing', 'Data Warehousing'),
            ('Hadoop', 'Hadoop'),
            ('Spark', 'Spark'),
            ('Data Science', 'Data Science'),
            ('Drupal', 'Drupal'),
            ('CMS', 'CMS'),
            ('Wordpress', 'Wordpress'),
            ('Shopify', 'Shopify'),
            ('Networking', 'Networking'),
            ('Information Technology', 'Information Technology')
        )
        model = models.Postings
        fields = ['title', 'location', 'techstack', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.Select(attrs={'class': "form-control"}, choices=loc_choices),
            'techstack': forms.SelectMultiple(attrs={'class': 'form-control'}, choices=tech_choices),
            'description': forms.Textarea(attrs={'class': 'form-control'})
        }